### ISSUE TITLE
Suggestions on getting to integrate with MegaRaid/LSI cards

### ISSUE THREAD

**Issue by shaneforsythe** [truenas/py-SMART#27]
I am testing on a Dell740 with LSI Raid card, and get the following error.

: /dev/sda Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/bin/shd", line 100, in <module>
    dev = Device(devpath.as_posix())
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pySMART/device.py", line 252, in __init__
    self.update()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pySMART/device.py", line 784, in update
    interface = smartctl_type[self.interface]
KeyError: '-d megaraid,N'

Any thoughts on how/where to proceed to try to get it working?

Thanks

**Comment by freqlabs** [comment]
Start here: https://github.com/freenas/py-SMART/blob/master/pySMART/device.py#L214

**Comment by ArminTinkered** [comment]
@shaneforsythe I was wondering the same thing about my controller card, which I use as an HBA.
```
import pySMART as smart
dev = smart.Device("/dev/sdb", abridged=True, smart_options="-d cciss,0 -a")
```
Try something like this, it's a hack IMHO, but readouts seem to work. Haven't tested anything else.
(in your case replace cciss with megaraid)

**Comment by ralequi** [comment]
@shaneforsythe please, check the last merge and check if now it works for you.
Feel free to close this issue when you have tested it.

**Comment by ralequi** [comment]
Please, open a new issue if you have any problem with LSI/MEGARAID cards, as far as they should be fully supported now
