### ISSUE TITLE
sda.assessment says "FAIL" but disk is not failing

### ISSUE THREAD

**Issue by l33333on** [truenas/py-SMART#34]
My program is sending the drive status via tcp. When it receives a specific string it return sda.assessment. Now sometimes it returns "FAIL". When Im reading the output of sda.assessment seperately in another python program it returns "PASS".

At first I set the device
sda = Device('/dev/sda')

Then, after every received string, I return sda.assessment

**Comment by l33333on** [comment]
Solved the problem by myself. The disk says that its temperature is at 77°C.... but the temperature is not changing at all....

**Comment by ralequi** [comment]
I'm going to close this issue as it seems there is no further help required
