### ISSUE TITLE
release current version to pypi.org

### ISSUE THREAD

**Issue by 07pepa** [truenas/py-SMART#35]
this is not yet availible for pip please make it so

**Comment by ralequi** [comment]
Until @william-gr generates a new release, remember you can use `pysmart @ git+https://github.com/truenas/py-SMART'` as your pip dep to use the current master-branch directly

**Comment by ralequi** [comment]
#20 seems to urge that release generation

**Comment by ralequi** [comment]
Does anybody have an email or way to contact Marc Herndon ?
@william-gr

**Comment by ralequi** [comment]
I have become an official maintainer. I'm going to publish a new version today.

The fork at https://pypi.org/project/pySMART.naudit/ is going to be closed soon.
