### ISSUE TITLE
Attributes list not populated

### ISSUE THREAD

**Issue by brendankristiansen** [truenas/py-SMART#37]
When creating a device (`dev = pySMART.Device('/dev/nvme0')`), the attributes list is always a list of `None`, as it is set in the device constructor. I am able to directly able to access attributes like temperature using `dev.temperature`, but we should be able to access the attributes array as well.

**Comment by ralequi** [comment]
Same here. smartctl version? Mine `smartctl 7.2 2021-01-17 r5171`

**Comment by brendankristiansen** [comment]
Mine is `smartctl 6.6 2016-05-31 r4324 [aarch64-linux-4.9.140]`

**Comment by ralequi** [comment]
The problem we were suffering was caused by the disks.

If smartctl -a does not generates the following list:

```SMART Attributes Data Structure revision number: 1                                              
Vendor Specific SMART Attributes with Thresholds:                                               
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
[...]
```

The attributes field won't be filled. And that fields are only generated if the disk support such counters/attributes.

**Comment by lowEagle** [comment]
Same here (smartctl 7.2 2020-12-30 r5155).
However, it seems as smartctl has a different output for (pci) NVMEs. It does not generate the same list but the following:

> smartctl -a /dev/nvme0
smartctl 7.2 2020-12-30 r5155 [x86_64-linux-5.4.140-1-pve] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

>=== START OF INFORMATION SECTION ===
Model Number:                       Samsung SSD 970 EVO Plus 500GB
Serial Number:                      S4EVNX0NA32843N
Firmware Version:                   2B2QEXM7
PCI Vendor/Subsystem ID:            0x144d
IEEE OUI Identifier:                0x002538
Total NVM Capacity:                 500.107.862.016 [500 GB]
Unallocated NVM Capacity:           0
Controller ID:                      4
NVMe Version:                       1.3
Number of Namespaces:               1
Namespace 1 Size/Capacity:          500.107.862.016 [500 GB]
Namespace 1 Utilization:            333.440.135.168 [333 GB]
Namespace 1 Formatted LBA Size:     512
Namespace 1 IEEE EUI-64:            002538 5a01b1770d
Local Time is:                      Wed Sep 15 13:04:55 2021 CEST
Firmware Updates (0x16):            3 Slots, no Reset required
Optional Admin Commands (0x0017):   Security Format Frmw_DL Self_Test
Optional NVM Commands (0x005f):     Comp Wr_Unc DS_Mngmt Wr_Zero Sav/Sel_Feat Timestmp
Log Page Attributes (0x03):         S/H_per_NS Cmd_Eff_Lg
Maximum Data Transfer Size:         512 Pages
Warning  Comp. Temp. Threshold:     85 Celsius
Critical Comp. Temp. Threshold:     85 Celsius

>Supported Power States
St Op     Max   Active     Idle   RL RT WL WT  Ent_Lat  Ex_Lat
 0 +     7.80W       -        -    0  0  0  0        0       0
 1 +     6.00W       -        -    1  1  1  1        0       0
 2 +     3.40W       -        -    2  2  2  2        0       0
 3 -   0.0700W       -        -    3  3  3  3      210    1200
 4 -   0.0100W       -        -    4  4  4  4     2000    8000

>Supported LBA Sizes (NSID 0x1)
Id Fmt  Data  Metadt  Rel_Perf
 0 +     512       0         0

>=== START OF SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

>SMART/Health Information (NVMe Log 0x02)
Critical Warning:                   0x00
Temperature:                        41 Celsius
Available Spare:                    100%
Available Spare Threshold:          10%
Percentage Used:                    0%
Data Units Read:                    593.252 [303 GB]
Data Units Written:                 1.954.515 [1,00 TB]
Host Read Commands:                 4.798.818
Host Write Commands:                7.767.267
Controller Busy Time:               18
Power Cycles:                       9
Power On Hours:                     15
Unsafe Shutdowns:                   4
Media and Data Integrity Errors:    0
Error Information Log Entries:      5
Warning  Comp. Temperature Time:    0
Critical Comp. Temperature Time:    0
Temperature Sensor 1:               41 Celsius
Temperature Sensor 2:               41 Celsius

>Error Information (NVMe Log 0x01, 16 of 64 entries)
No Errors Logged

**Comment by ralequi** [comment]
Old attributes can't be readed from NVME devices.
However, it might be useful to take some other metrics such as:

>Available Spare: 100%
Available Spare Threshold: 10%
Percentage Used: 0%
Data Units Read: 593.252 [303 GB]
Data Units Written: 1.954.515 [1,00 TB]
Host Read Commands: 4.798.818
Host Write Commands: 7.767.267
Controller Busy Time: 18
Power Cycles: 9
Power On Hours: 15
Unsafe Shutdowns: 4

Maybe "diags" section will be the place to store such data. What do you think?

**Comment by lowEagle** [comment]
Sounds good to me. However, as I am using the script to get the drive state but also the temperatures of my drives, I would really like to also have access to
>Temperature: 41 Celsius
Temperature Sensor 1: 41 Celsius
or
Temperature Sensor 2: 41 Celsius

Yet this might not be that easy as currently the temperature is part of the attributes and not diagnostics.

**Comment by ralequi** [comment]
Temperature is stored as part of the main device info:

```python3
class Device(object):
# [...]
        self.temperature: int = None
        """
        **(int or None): Since SCSI disks do not report attributes like ATA ones
        we need to grep/regex the shit outta the normal "smartctl -a" output.
        In case the device have more than one temperature sensor the first value
        will be stored here too.
        """
        self.temperatures = {}
        """
        **(dict of int): NVMe disks usually report multiple temperatures, which
        will be stored here if available. Keys are sensor numbers as reported in
        output data.
        """
# [...]
```

Also, multiple "temperature" definitions are stored as a dict on self.temperatures

**Comment by lowEagle** [comment]
Thank you for the hint, I could have seen that..
So I guess storing the NVME info the in diag section is the best way to go.

**Comment by ralequi** [comment]
There has been no movement in almost a year.

If you need more help, please, feel free to re-open this issue or a new one.
