### ISSUE TITLE
sda.attributes issue on Windows 10

### ISSUE THREAD

**Issue by Shaver443** [truenas/py-SMART#45]
Running into an issue with getting the attributes of a device.

The code I'm running is...
`from pySMART import Device

sda = Device('/dev/sda')

print(sda.all_attributes())`

I get this output...
`C:\Users\Austin\Projects\Python>c:/python310/python.exe c:/Users/Austin/Projects/Python/test2.py
ID# ATTRIBUTE_NAME          CUR WST THR TYPE     UPDATED WHEN_FAIL   RAW
Traceback (most recent call last):
  File "c:\Users\Austin\Projects\Python\test2.py", line 5, in <module>
    print(sda.all_attributes())
  File "c:\python310\lib\site-packages\pySMART\device.py", line 398, in all_attributes
    print_fn(attr)
  File "c:\python310\lib\site-packages\pySMART\attribute.py", line 139, in __str__
    self.thresh,
  File "c:\python310\lib\site-packages\pySMART\attribute.py", line 107, in thresh
    return int(self._thresh)
ValueError: invalid literal for int() with base 10: '---'`

Any ideas?

I'm running python 3.10.

**Comment by ralequi** [comment]
Hi @Shaver443 ,

The main issue there, is that Windows 10 does not enum the devices like linux, so probably you don't have `/dev/sda` device.
¿Are you running under WSL?

I will require to analyze this in deep the full output of the following commands:

- `smartctl --scan-open`
- `smartctl --all /dev/sda`

And, if you agree, I could store the results of those commands under tests folders, so "windows-like" environments like yours could be tested on future versions.

Thank you for submitting the issue

**Comment by ralequi** [comment]
@Shaver443 could you provide the requested info please?

**Comment by ralequi** [comment]
As there were no more info, I'm closing this issue.

Please feel free to reopen/open new issues if you find any other problem/bug/request.

Thank you.
