### ISSUE TITLE
Nvme device: ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by ulmitov** [truenas/py-SMART#52]
In [1]: import pySMART

In [3]: pySMART.SMARTCTL.sudo = True

In [4]: devlist = pySMART.DeviceList()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [4], line 1
----> 1 devlist = pySMART.DeviceList()

File ~/.local/lib/python3.10/site-packages/pySMART/device_list.py:63, in DeviceList.__init__(self, init, smartctl)
     60 """The smartctl wrapper
     61 """
     62 if init:
---> 63     self._initialize()

File ~/.local/lib/python3.10/site-packages/pySMART/device_list.py:110, in DeviceList._initialize(self)
    107         name = groups[0]
    108         interface = groups[1]
    109         self.devices.append(
--> 110             Device(name, interface=interface, smartctl=self.smartctl))
    112 # Remove duplicates and unwanted devices (optical, etc.) from the list
    113 self._cleanup()

File ~/.local/lib/python3.10/site-packages/pySMART/device.py:283, in Device.__init__(self, name, interface, abridged, smart_options, smartctl)
    280 # If a valid device was detected, populate its information
    281 # OR if in unabridged mode, then do it even without interface info
    282 if self.interface is not None or self.abridged:
--> 283     self.update()

File ~/.local/lib/python3.10/site-packages/pySMART/device.py:853, in Device.update(self)
    848 #######################################
    849 #   Dedicated interface attributes    #
    850 #######################################
    852 if interface == 'nvme':
--> 853     self.if_attributes = NvmeAttributes(iter(_stdout))
    854 else:
    855     self.if_attributes = None

File ~/.local/lib/python3.10/site-packages/pySMART/interface/nvme.py:483, in NvmeAttributes.__init__(self, data)
    480 self.errors: List[NvmeError] = []
    482 if data is not None:
--> 483     self.parse(data)

File ~/.local/lib/python3.10/site-packages/pySMART/interface/nvme.py:526, in NvmeAttributes.parse(self, data)
    523     self.percentageUsed = int(value[:-1])
    524 elif name == 'Data Units Read':
    525     # Format: 1,234,567 [2.00 TB]
--> 526     self.dataUnitsRead = int(
    527         value.split(' ')[0].replace(',', '').replace('.', ''))
    528     self.bytesRead = humanfriendly.parse_size(
    529         value.split(' ', 1)[1][1:-1].replace(',', '.'))
    530 elif name == 'Data Units Written':
    531     # Format: 1,234,567 [2.00 TB]

ValueError: invalid literal for int() with base 10: '667\u202f413'

`smartctl --scan-open`
/dev/nvme0 -d nvme # /dev/nvme0, NVMe device

`sudo smartctl --info /dev/nvme0n1`
smartctl 7.2 2020-12-30 r5155 [x86_64-linux-5.15.0-53-generic] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       WDC WDS100T2B0C-00PXH0
Serial Number:                      220312800929
Firmware Version:                   233010WD
PCI Vendor/Subsystem ID:            0x15b7
IEEE OUI Identifier:                0x001b44
Total NVM Capacity:                 1 000 204 886 016 [1,00 TB]
Unallocated NVM Capacity:           0
Controller ID:                      0
NVMe Version:                       1.4
Number of Namespaces:               1
Namespace 1 Size/Capacity:          1 000 204 886 016 [1,00 TB]
Namespace 1 Formatted LBA Size:     512
Namespace 1 IEEE EUI-64:            001b44 8b45ea9cce

**Comment by ralequi** [comment]
The value `Data Units Read` is not present on the smartctl provided...

¡Second interesting issue of the day!

Please, provide the output as the last time:
`sudo smartctl --all /dev/nvme0n1`

**Comment by ralequi** [comment]
there should be something weird with your setup.

I suppose it should be related with lang/location, but not sure why.

The character ` ` that is returned by your smartctl should be just a comma `,`.

I'm going to consider this as a corner case and support it... but I would appreciate if you can share the env variables or other conditions that may lead to this anomalous behaviour .

Thank you in advance

**Comment by ralequi** [comment]
Try the develop release (you can install using `pip install git+https://github.com/truenas/py-SMART@develop`) and tell me if it is fixed or not.

Add here any other utf8/encoding issues you found out there.

Thank you for your time.

**Comment by ralequi** [comment]
I'm closing this issue then.

I would double-check this as it seems there is something strange on windows with this character. I'll try to fix it before merge the fix into master.

Thanks again!
