### ISSUE TITLE
Enhancement request: please create an exec method in smartcl class

### ISSUE THREAD

**Issue by ulmitov** [truenas/py-SMART#54]
Hi,
To be able to run with different types of host communications, please add an exec method which will hold these lines from smartctl.generic_call:

def exec(cmd):
        cmd = Popen(cmd, stdout=PIPE, stderr=PIPE)
        _stdout, _stderr = [i.decode('utf8') for i in cmd.communicate()]
        return _stdout.split('\n'), cmd.returncode

**Comment by ralequi** [comment]
Well, I thought overloading `generic_call` was going to be enough .

Just curiosity, which kind of communication are you looking for?

**Comment by ralequi** [comment]
Thank you!

Btw, mail me if you are interested on a job position on a Spanish mid-size tech company. (Naudit HPCN)
