### ISSUE TITLE
Please add xall method

### ISSUE THREAD

**Issue by ulmitov** [truenas/py-SMART#55]
Hi,

Please add this method in smartctl object
`
    def xall(self, disk_type: str, disk: str) -> List[str]:
        """Queries smartctl with option --xall

        Args:
            disk_type (str): the disk type (interface)
            disk (str): the disk os-full-path

        Returns:
            List[str]: A raw line-by-line output from smartctl
        """
        return self.generic_call(['-d', disk_type, '-x', disk], pass_options=True)[0]
`

**Comment by ralequi** [comment]
Didn't know that command exists.
Probably it should be explored as well at some point
