### ISSUE TITLE
Graceful device init

### ISSUE THREAD

**Issue by ulmitov** [truenas/py-SMART#59]
Hi,

If some corner case happens and DeviceList raises exception on Device init, could you add please a try except option over it ? (but still print the exception) - that's for being able to work with the other drives anyway even if one failed to init

Thanks!

**Comment by ralequi** [comment]
Hi @ulmitov ,

Try `DeviceList(catch_errors=True)` and tell me if that suits your request.

As always, thanks for your suggestions!

**Comment by ralequi** [comment]
It will be printed anyways (that's how logger.exception works)

**Comment by ralequi** [comment]
Also, logger.exception will print the stack trace ;-)
