### ISSUE TITLE
pystorcli2

### ISSUE THREAD

**Issue by ulmitov** [truenas/py-SMART#62]
Hey @ralequi,

I've seen you have ownership over pystorcli2, very nice! you have a monopoly, haha)).
I've tried to use it but there some bugs, in the project i can't open a ticket, can i report some issues on that package ?
For instance,

```
pip install  pystorcli2
Defaulting to user installation because normal site-packages is not writeable
Collecting pystorcli2
  Downloading PyStorCLI2-0.5.0-py3-none-any.whl (22 kB)
Installing collected packages: pystorcli2
Successfully installed pystorcli2-0.5.0

In [1]: import pystorcli2

In [3]: pystorcli2.Controllers()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [3], line 1
----> 1 pystorcli2.Controllers()

AttributeError: module 'pystorcli2' has no attribute 'Controllers'
```

**Comment by ralequi** [comment]
Hey @ulmitov !
I don't work on Truenas corp so, I don't feel confortable to mix issues.
Please, open this issue on https://github.com/Naudit/pystorcli2

**Comment by ralequi** [comment]
oh my...
Sure, didn't realize that... Thanks @ulmitov

**Comment by ralequi** [comment]
oh my...
Sure, didn't realize that... Thanks @ulmitov
Just try again
