### ISSUE TITLE
how to work with disks /dev/sg[1,2]

### ISSUE THREAD

**Issue by Nikolay-Gamzin** [truenas/py-SMART#70]
**Describe the bug**
from pySMART import Device
>>> sg1 = Device('/dev/sg1')
/usr/local/lib/python3.4/dist-packages/pySMART/device.py:160: UserWarning: 
Device '/dev/sg1' does not exist! This object should be destroyed.
>>> sg1 = Device('/dev/sg2')
/usr/local/lib/python3.4/dist-packages/pySMART/device.py:160: UserWarning: 
Device '/dev/sg2' does not exist! This object should be destroyed.

disk.type 'scsi'

**Raw outputs**
smartctl -a /dev/sg2
smartctl 6.4 2014-10-07 r4002 [x86_64-linux-4.9.0-0.bpo.12-amd64] (local build)
Copyright (C) 2002-14, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Device Model:     ST2000NM000A-2J2100
Serial Number:    WS10SM2A
LU WWN Device Id: 5 000c50 0f129bee9
Firmware Version: TN03
User Capacity:    2 000 398 934 016 bytes [2,00 TB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    7200 rpm
Form Factor:      3.5 inches
Device is:        Not in smartctl database [for details use: -P showall]
ATA Version is:   Unknown(0x0fe0) (minor revision not indicated)
SATA Version is:  SATA >3.2, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Mon May 22 13:09:29 2023 MSK
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x82)	Offline data collection activity
					was completed without error.
					Auto Offline Data Collection: Enabled.
Self-test execution status:      (   0)	The previous self-test routine completed
					without error or no self-test has ever 
					been run.
Total time to complete Offline 
data collection: 		(  567) seconds.
Offline data collection
capabilities: 			 (0x7b) SMART execute Offline immediate.
					Auto Offline data collection on/off support.
					Suspend Offline collection upon new
					command.
					Offline surface scan supported.
					Self-test supported.
					Conveyance Self-test supported.
					Selective Self-test supported.
SMART capabilities:            (0x0003)	Saves SMART data before entering
					power-saving mode.
					Supports SMART auto save timer.
Error logging capability:        (0x01)	Error logging supported.
					General Purpose Logging supported.
Short self-test routine 
recommended polling time: 	 (   1) minutes.
Extended self-test routine
recommended polling time: 	 ( 196) minutes.
Conveyance self-test routine
recommended polling time: 	 (   2) minutes.
SCT capabilities: 	       (0x50bd)	SCT Status supported.
					SCT Error Recovery Control supported.
					SCT Feature Control supported.
					SCT Data Table supported.

SMART Attributes Data Structure revision number: 10
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x000f   082   064   044    Pre-fail  Always       -       148350832
  3 Spin_Up_Time            0x0003   096   096   000    Pre-fail  Always       -       0
  4 Start_Stop_Count        0x0032   100   100   020    Old_age   Always       -       39
  5 Reallocated_Sector_Ct   0x0033   100   100   010    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x000f   072   060   045    Pre-fail  Always       -       16886160
  9 Power_On_Hours          0x0032   099   099   000    Old_age   Always       -       1380
 10 Spin_Retry_Count        0x0013   100   100   097    Pre-fail  Always       -       0
 12 Power_Cycle_Count       0x0032   100   100   020    Old_age   Always       -       39
 18 Unknown_Attribute       0x000b   100   100   050    Pre-fail  Always       -       0
187 Reported_Uncorrect      0x0032   100   100   000    Old_age   Always       -       0
188 Command_Timeout         0x0032   100   100   000    Old_age   Always       -       0
190 Airflow_Temperature_Cel 0x0022   069   066   040    Old_age   Always       -       31 (Min/Max 25/32)
192 Power-Off_Retract_Count 0x0032   100   100   000    Old_age   Always       -       38
193 Load_Cycle_Count        0x0032   100   100   000    Old_age   Always       -       97
194 Temperature_Celsius     0x0022   031   040   000    Old_age   Always       -       31 (0 22 0 0 0)
195 Hardware_ECC_Recovered  0x001a   082   064   000    Old_age   Always       -       148350832
197 Current_Pending_Sector  0x0012   100   100   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0010   100   100   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x003e   200   200   000    Old_age   Always       -       0
240 Head_Flying_Hours       0x0000   100   253   000    Old_age   Offline      -       1369 (143 119 0)
241 Total_LBAs_Written      0x0000   100   253   000    Old_age   Offline      -       1105531559
242 Total_LBAs_Read         0x0000   100   253   000    Old_age   Offline      -       13287203134

SMART Error Log Version: 1
No Errors Logged

SMART Self-test log structure revision number 1
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Extended offline    Completed without error       00%      1284         -
# 2  Short offline       Completed without error       00%      1281         -

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.

**Environmental setup:**
 - Complete smartctl version [e.g. `smartctl 6.4 2014-10-07 r4002 [x86_64-linux-4.9.0-0.bpo.12-amd64] (local build)`]
 - Py-SMART version [e.g. `v1.2.4`]

**Comment by Nikolay-Gamzin** [comment]
smartctl -a /dev/sg0
smartctl 6.4 2014-10-07 r4002 [x86_64-linux-4.9.0-0.bpo.12-amd64] (local build)
Copyright (C) 2002-14, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               LSI
Product:              Logical Volume
Revision:             3000
Compliance:           SPC-4
User Capacity:        1 998 998 994 944 bytes [1,99 TB]
Logical block size:   512 bytes
Logical Unit id:      0x600508e000000000ee7ac70678be2807
Device type:          disk
Local Time is:        Mon May 22 13:18:42 2023 MSK
SMART support is:     Unavailable - device lacks SMART capability.

=== START OF READ SMART DATA SECTION ===

Error Counter logging not supported

Device does not support Self Test logging

**Comment by ralequi** [comment]
In the /dev/sg0 case, it's normal that virtual (raid) devices does not provides SMART info.

In the other disks scenario, let me check if I can replicate it from your data

**Comment by ralequi** [comment]
Hi @Nikolay-Gamzin 

I can't replicate your issue on pySmart 1.2.4.

On the first hand, If I take your output and notify pySmart that is a "SATA" device, everything got correctly readed.
I will need the output of `smartctl -d test /dev/sg2` to check if pysmart is detecting the correct device type.

In the other hand, and according to your output, you are not using PySmart 1.2.4 but the alfa version `FN-10.2-ALPHA`. I don't know why you got there... specially that version were released on 2015. Can you check with pip which version are really installed?

**Comment by Nikolay-Gamzin** [comment]
Hi @ralequi 
smartctl -d test /dev/sg2
smartctl 6.4 2014-10-07 r4002 [x86_64-linux-4.9.0-0.bpo.12-amd64] (local build)
Copyright (C) 2002-14, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/sg2: Device of type 'scsi' [SCSI] detected
/dev/sg2 [SAT]: Device open changed type from 'scsi' to 'sat'
/dev/sg2 [SAT]: Device of type 'sat' [ATA] opened

Regarding the version of pySMART - exactly, there is an old version of python3.4 and an old version of pySMART.
Probably until it is updated there is no point in checking something =(

**Comment by ralequi** [comment]
Sorry but can't help with such older versions...
You can try to copy the code from one of the earlier tags and pray it works on your python version... but can't promise anything.

With the latest output provided I can confirm the device is correctly detected & parsed on the latest pysmart version.
I'm closing this issue now.

Feel free to open new issues If you found anything else new (or reopen this).
Good luck!
