### ISSUE TITLE
Parse error on windows env?

### ISSUE THREAD

**Issue by wolfdate25** [truenas/py-SMART#73]
**Describe the bug**
I got error with windows enviroment
![image](https://github.com/truenas/py-SMART/assets/4906999/c767d3a4-9a78-4e42-a11e-c7e16ea6d595)
![image](https://github.com/truenas/py-SMART/assets/4906999/a85a7c74-0037-4c47-927e-8a7643f553ab)

The tools working with native commands.
With pySMART wrapper, I got upper image errors.

**Environmental setup:**
 - smartctl 7.3 2022-02-28 r5338 [x86_64-w64-mingw32-w11-b22621] (sf-7.3-1)
 - Py-SMART version v1.2.5
 - windows 11
 - AMD RAID

**Comment by ralequi** [comment]
On a first look, It seems to be a charset issue

Please, provide the following outputs:

- `smartctl --scan-open`
- `smartctl -d test /dev/sda`

**Comment by wolfdate25** [comment]
`smarttl --scan-open`
```
/dev/sda -d nvme # /dev/sda, NVMe device
/dev/sdb -d nvme # /dev/sdb, NVMe device
/dev/sdc -d sat # /dev/sdc [SAT], ATA device
/dev/sdd -d scsi # /dev/sdd, SCSI device
/dev/sde -d scsi # /dev/sde, SCSI device
```
`smartctl -d test /dev/sda`
```
smartctl 7.3 2022-02-28 r5338 [x86_64-w64-mingw32-w11-b22621] (sf-7.3-1)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/sda: Device of type 'nvme' [NVMe] detected
/dev/sda: Device of type 'nvme' [NVMe] opened
```

**Comment by ralequi** [comment]
Please, also include the output of

`smartctl -d nvme /dev/sda`

Since it is windows, I would prefer to upload the raw output instead of copy it (just in case is some strange issue with char coding)

For that, please, run `smartctl -d nvme /dev/sda > out.txt` and upload that file without any modification.

If you have any issue uploading the file, copying the text it's ok, but, if the issue is related with char-coding I wouldn't find anything.

Thank you in advance.

**Comment by wolfdate25** [comment]
I'm using windows UTF-8 encoding.
[Downloads.zip](https://github.com/truenas/py-SMART/files/11848991/Downloads.zip)

**Comment by ralequi** [comment]
Hi,

I suppose the out3.txt is the result of `smartctl -d nvme /dev/sda` right?

```
smartctl 7.3 2022-02-28 r5338 [x86_64-w64-mingw32-w11-b22621] (sf-7.3-1)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

NVMe device successfully opened

Use 'smartctl -a' (or '-x') to print SMART (and more) information

``` 

There is no "real data" on there, could you please provide `smartctl -d nvme --all /dev_sda` ?

**Comment by wolfdate25** [comment]
Yes, there is no valuable data there.
And here the result of `smartctl -d nvme --all /dev/sda`
[out4.zip](https://github.com/truenas/py-SMART/files/11867531/out4.zip)

**Comment by ralequi** [comment]
Sorry @wolfdate25 , I hadn't too much time for this.
Very strange scenario, look at this lines:

```
Total NVM Capacity:                 0
Unallocated NVM Capacity:           18,446,742,073,310,617,600 [18446 PB]
[...]
Number of Namespaces:               1
Namespace 1 Size/Capacity:          2,000,398,934,016 [2.00 TB]
Namespace 1 Formatted LBA Size:     512
Namespace 1 IEEE EUI-64:            a84397 0000677720
```

¿¿18446 PB?? There is something very strange with your drive and/or smarmatctl tool. In any case, time to handle this corner case....

**Comment by ralequi** [comment]
Will be "Fixed" on next release

**Comment by ralequi** [comment]
Try develop branch and confirm that everything works for you when you are able 

Thanks for your contrib

**Comment by wolfdate25** [comment]
It's late, but we're happy to report that it's been resolved.
