### ISSUE TITLE
Minor typo in NvmeAttributes() class

### ISSUE THREAD

**Issue by petersulyok** [truenas/py-SMART#81]
In the latest github version there is minor typo in `./pySMART/interface/nvme/__init__.py` file, line 536:

`self.critialWarning: Optional[int] = None`

The 'c' is missing from critical. Later the right name is used in the code and in the comments.
I wanted to create a pull request to fix it but this repo seems to be closed.

**Comment by petersulyok** [comment]
Thanks for the fix.

I received this error message in PyCharm when I pushed my pull request:
`Can't create a new pull request: Push failed: remote: Permission to truenas/py-SMART.git denied to petersulyok. unable to access 'https://github.com/truenas/py-SMART.git/': The requested URL returned error: 403`

I could be an PyCharm issue, usually I don't have any issue with my repos.

**Comment by ralequi** [comment]
Hi, bug fixed and published as dev release: https://pypi.org/project/pySMART/1.3.1.dev5/

Ok, that seems that you have tried to push directly to the repo. That's not how github works on non-owned repos.

Normally you have to:
1- fork the project
2- push your commits to **your** project fork
3- create a new "pull request" from **your** repo to the **original** one

Yeah, I know. The first time you see it is ugly, agree. But if you think further it makes the code protected from unreviewed commits.

In any case, thanks for your report. I expect you didn't waste much time annoyed by that typo. Those "stupid typos/errors" are typically highly time consuming to detect

**Comment by petersulyok** [comment]
Thanks for the clarification. Will do next time.
