### ISSUE TITLE
Does not work on OSX

### ISSUE THREAD

**Issue by evanrich** [truenas/py-SMART#84]
**Describe the bug**
Running on OSX, devicelist does not return anything:

```
>>> from pySMART import SMARTCTL
>>> SMARTCTL.sudo = True
>>> devlist = DeviceList()
>>> devlist
<DeviceList contents:
>
>>>
```

However, if you define a device, it can see the disk:
```
 from pySMART import SMARTCTL
SMARTCTL.sudo = True
from pySMART import Device
 disk3 = Device('/dev/disk3')
disk3
<NVME device on /dev/disk3 mod:APPLE SSD AP0512Z sn:0ba0224b2254ca3c>

```
**Raw outputs**
Please, provide the following raw command outputs to be added to our test-base. Notify explicitly if you don't want them to be incorporated. In any case, they are "mostly required" to check and verify your issue/bug.

- `smartctl --scan-open`
```
martctl --scan-open
IOService:/AppleARMPE/arm-io@10F00000/AppleT811xIO/ans@77400000/AppleASCWrapV4/iop-ans-nub/RTBuddy(ANS2)/RTBuddyService/AppleANS3NVMeController/NS_01@1 -d nvme # IOService:/AppleARMPE/arm-io@10F00000/AppleT811xIO/ans@77400000/AppleASCWrapV4/iop-ans-nub/RTBuddy(ANS2)/RTBuddyService/AppleANS3NVMeController/NS_01@1, NVMe device
```

- `smartctl --all <problematic device> # Example: smartctl --all /dev/nvme0`
```
smartctl --all /dev/disk3
smartctl 7.4 2023-08-01 r5530 [Darwin 23.2.0 x86_64] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       APPLE SSD AP0512Z
Serial Number:                      0ba0224b2254ca3c
Firmware Version:                   359.60.3
PCI Vendor/Subsystem ID:            0x106b
IEEE OUI Identifier:                0x000000
Controller ID:                      0
NVMe Version:                       <1.2
Number of Namespaces:               3
Local Time is:                      Thu Mar 28 15:22:22 2024 PDT
Firmware Updates (0x02):            1 Slot
Optional Admin Commands (0x0004):   Frmw_DL
Optional NVM Commands (0x0004):     DS_Mngmt
Maximum Data Transfer Size:         256 Pages

Supported Power States
St Op     Max   Active     Idle   RL RT WL WT  Ent_Lat  Ex_Lat
 0 +     0.00W       -        -    0  0  0  0        0       0

=== START OF SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

SMART/Health Information (NVMe Log 0x02)
Critical Warning:                   0x00
Temperature:                        19 Celsius
Available Spare:                    100%
Available Spare Threshold:          99%
Percentage Used:                    0%
Data Units Read:                    499,872 [255 GB]
Data Units Written:                 695,150 [355 GB]
Host Read Commands:                 14,376,794
Host Write Commands:                12,469,540
Controller Busy Time:               0
Power Cycles:                       61
Power On Hours:                     10
Unsafe Shutdowns:                   8
Media and Data Integrity Errors:    0
Error Information Log Entries:      0

Read 1 entries from Error Information Log failed: GetLogPage failed: system=0x38, sub=0x0, code=745
```

**Environmental setup:**
 - Complete smartctl version [e.g. `smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.0.10-300.fc37.x86_64]`]
 ```
smartctl 7.4 2023-08-01 r5530 [Darwin 23.2.0 x86_64] (local build)
```
 - Py-SMART version [e.g. `v1.2.0`]: 1.3.0

**Comment by evanrich** [comment]
FYI This is on latest Sonoma 15.3 (Mac Mini M2)

**Comment by ralequi** [comment]
Hi,

Thanks for submitting this issue.

Could you please try to run the following command and paste its output here?

`smartctl -d nvme --all 'IOService:/AppleARMPE/arm-io@10F00000/AppleT811xIO/ans@77400000/AppleASCWrapV4/iop-ans-nub/RTBuddy(ANS2)/RTBuddyService/AppleANS3NVMeController/NS_01@1'`

That's the internal command being executed by pysmart

**Comment by ralequi** [comment]
Hi @evanrich 

It looks like the disk is being discarded from the list because it does not provides any capacity metrics, so it is being considered invalid.

Please, provide the output of the requested command when you are able. I would like to see if it provides something different from the provided output before considering this a bug or not

**Comment by ralequi** [comment]
should be fixed on https://github.com/truenas/py-SMART/commit/e34e30ef4494e20860415a2f8608656edea36d1d , check on newer version and reopen if the issue still persists.

Thanks for your contrib
