### ISSUE TITLE
bug should be _len not len

### ISSUE THREAD

**Issue by guanfeix** [truenas/py-SMART#88]
![image](https://github.com/truenas/py-SMART/assets/34960209/caef8774-2c73-4645-840d-8f1caaea7a14)

**Comment by ralequi** [comment]
Hi,

I need to check. Looks too obvious bug to not have been detected before.

Thanks for your report

**Comment by ralequi** [comment]
Thanks for your contrib @guanfeix , will be pushed to pypi soon
